In [1]:
#pytorch Fundamentals
import torch
import pandas
print (torch.__version__)
import numpy as np
import matplotlib.pyplot as plt



2.5.1+cu121


#creating tensors

In [2]:
#introduction to tensors
scalar = torch.tensor(7)
scalar

tensor(7)

Pytorch tensors are created using torch.tensors

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python int
scalar.item()

7

In [5]:

#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim
#how many n number of matrix has dimensions
MATRIX[0]


tensor([7, 8])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
#tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])# three square bracket making it more contagious

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim
TENSOR.shape

torch.Size([1, 3, 3])

#random tensors

In [13]:
#random tensors
#Why are random tensors important?
#they are imp becoz the way neural networks learn is that they start with tensors
#full of random numbers and them adjust those random numbers to
#better represent the idea

#Start with random numbers>>>look at data >>> update random numberss >>look at data >>update


In [14]:
#create a random tensor of shape ( 3, 4)
random_tensor  = torch.rand(3,4)
random_tensor

tensor([[0.2331, 0.6677, 0.1205, 0.9834],
        [0.7121, 0.7161, 0.1183, 0.3009],
        [0.1168, 0.3352, 0.7372, 0.1276]])

In [15]:
random_tensor.ndim


2

In [16]:
#create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(224,224,3))#height,width,color channels(R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [17]:
torch.rand(size=(3,3))

tensor([[0.8793, 0.5479, 0.1329],
        [0.0067, 0.5818, 0.9122],
        [0.8461, 0.7810, 0.4205]])

#zeros and ones

In [18]:
#zeros and ones
#create a tensor of all zeroes
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
#create a tensor of all ones
ones= torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

In [22]:
random_tensor.dtype

torch.float32

#creating a range of tensors and tensors-like

In [23]:
# use torch.range()
#use torch.range ND GET DEprecated ,message , use torch.arange
one_to_ten = torch.arange(start=1 , end=1000 , step=77)
one_to_ten




tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [24]:
# creating tensors like
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#tensor datatypes

In [25]:
### Tensor datatypes
float_32_tensor =  torch.tensor([3.0,6.0,9.0])

float_32_tensor.dtype
float_16_tensor = float_32_tensor.type(torch.float16)



tensor data types are one of the big theree issues in pytorch
1. tenors not right datatype
2. tensors not right shape
3. tensors not on the right device

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype


torch.float16

In [27]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

#Getting

In [28]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32) # Changed dtype to torch.int32
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [29]:

float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

#getting information from tensors

1.tensors not right datatype-- to egt the from a tensor use tensor.dtype
2. tensor not right shape--to get shape from the tensor

3. tensors not on the right device--to get device from a tensor , can use tensor.device

In [31]:
#how do we check the datatype
#how do we check device /
# To get the shape of tensor
some_tensor = torch.rand(3,4)
some_tensor



tensor([[0.6241, 0.9811, 0.3593, 0.1955],
        [0.9300, 0.4091, 0.7416, 0.2429],
        [0.0103, 0.5500, 0.5029, 0.0192]])

In [32]:
#find out some details about the tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6241, 0.9811, 0.3593, 0.1955],
        [0.9300, 0.4091, 0.7416, 0.2429],
        [0.0103, 0.5500, 0.5029, 0.0192]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [33]:
some_tensor.size , some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [34]:
some_tensor.size()

torch.Size([3, 4])

#manipulating tensor / tensor operation

In [34]:
#manipulating tensor operations
tensor operation include
* addition
* subtraction
* multiplication (element-wise)
* division
* matrix multiplication

In [36]:
#create a tensor
tensor = torch.tensor([1,2,3])

tensor + 10

tensor([11, 12, 13])

In [39]:
#multiply tensor by 10
tensor = tensor * 10

In [41]:
tensor - 10

tensor([ 90, 190, 290])

In [42]:
#try out pytorch in-built functions
torch.mul(tensor,10)

tensor([1000, 2000, 3000])

In [43]:
torch.add(tensor,10)

tensor([110, 210, 310])

#Matrix multiplication

Two main ways of performing matrix multiplication in deep learning:


In [44]:
 #element wise multiplication
 tensor = torch.tensor([1,2,3])
 print(tensor, "*", tensor)
 print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [45]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor

In [ ]:
#matrix multiplication by hand
1*1 + 2*2 + 3*3

In [ ]:
value = 0
for i in range (len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

In [ ]:
#time
%%time
value = 0
for i in range (len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

In [ ]:
#time
torch.matmul (tensor,tensor)