In [4]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [5]:
import torch 

In [6]:
import torch

# shapes for matrix multiplication 
tensor_A = torch.tensor([[1, 2],    # Note the extra square brackets
                        [3, 4],
                        [5, 6]])    # All rows wrapped in one outer list

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

# Fixed function name too (matmul not matmull)
torch.matmul(tensor_B.T, tensor_A)  # Transposing B to make dimensions match

tensor([[ 76, 100],
        [103, 136]])

Tensor shape issues , we can manipulate the shape of a tensor using transpose 
A transpose  switches the axes or dimensions of a given tensor 

In [7]:
tensor_B.T , tensor_B.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([3, 2]))

In [8]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [9]:
# The matrix multiplication operation works when tesnsor_B is tramsposed 
print(f"original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("output:\n")
print(torch.matmul(tensor_A, tensor_B.T))

original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


## Tensor aggregation
min max mean sum (tensor aggregation 

In [10]:
#create a tensor 
x = torch.arange(0,100,10)
x , x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [11]:
#find the min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [12]:
#find the max 
torch.max(x), x.max()

(tensor(90), tensor(90))

In [13]:
#find the mean 
torch.mean(x.type(torch.float32)), x.type (torch.float32).mean ()

(tensor(45.), tensor(45.))

In [14]:
#find the sum 
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# finding the positional min and max 

In [15]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
#finding the positional min and max 
#find the position in tensor that has minimum value with argmin
x.argmin()


tensor(0)

In [17]:
#find the position in tensor that has max value with argmax
x.argmax()

tensor(9)

In [18]:
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

# reshaping , stacking , squeezing and squeezing

In [19]:
#reshaping , stacking , squeezing and squeezing 

#* Reshaping - reshape an input tensor to a defined shape 
#* view - return a view of an input tensor of a certain shape but keep memory as the original tensor  
#* stacking - combine multiple tensors on top of each other (vstack) or side by 
 #side (hstack)
#*squeeze - removes all "l " dimensions from a tensor 
#* unsqueeze - add a 1 dimension to a target tensor 
#* permute - Return a view of the input with dimensions permuted (swapped ) in a certain way


In [20]:
#lets create a tensor 
import torch 
x = torch.arange(1., 10.)
x , x.shape 

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [21]:
#add an extra dimension 
x_reshaped = x.reshape(1,9)
x_reshaped , x_reshaped.shape 

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

# change  the view 

In [22]:
#add an extra dimension 
# change  the view 
z = x.view ( 1,9)
z , z.shape 

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [23]:
#changing z changes x ( because a view of a tensor shaes the memory as original )
z[:,0] = 5 
z , x 

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [24]:
#stack tensors on the top of other 
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked 

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [25]:
#torch.squeeze ()-- remove all single dimensions from the target tensor 
x_reshaped 

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [26]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [27]:
x_reshaped 

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [28]:
print(f"previous tensor: {x_reshaped}")
print(f"previous shape : {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\n New Tensor : { x_reshaped } ")
print(f" new Shape : {x_squeezed.shape}")


previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape : torch.Size([1, 9])

 New Tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) 
 new Shape : torch.Size([9])


In [29]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
x_reshaped.squeeze().shape 

torch.Size([9])

In [31]:
#torch unsqueeze -- add a single dimension to the target tensor at a specific dim(dimension)
print (f"previous target : { x_squeezed} ")
print (f"previous target : { x_squeezed.shape} ")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\n new tensor : { x_unsqueezed} ")
print(f"\n new shape : { x_unsqueezed.shape} ")

previous target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) 
previous target : torch.Size([9]) 

 new tensor : tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) 

 new shape : torch.Size([9, 1]) 


In [32]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
x_reshaped.squeeze().shape

torch.Size([9])

#Torch.permute 

In [34]:
#torch.permute --- rearrange the target 
#we can use this with images 
x_original = torch.rand(size=(224,224,3))#[height width and color channels] 

#permute the original tensor to rearrange the axis (or dim) order 
x_permute = x_original.permute(2, 0 , 1) # shifts axis 0-> 1 , 1->2, 2->0
print(f"\n previous shape: { x_original.shape} ")
print(f"\n new shape : { x_permuted.shape} ") #[color_channels , height , width]



 previous shape: torch.Size([224, 224, 3]) 


NameError: name 'x_permuted' is not defined

In [ ]:
x_original [0,0,0]== 72818
x_original [0,0,0], x_permuted[0,0,0]

#indexing ( collecting data from tensor

In [ ]:
import torch 
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

In [ ]:
#lets index on a new tensor 
x[0]

In [ ]:
#lets index on middle bracket (dim=1)
x[0][0]

In [ ]:
#lets index on the most inner bracket (last dimension )
x[0][1][1]

In [ ]:
#you can use ":" to select all of a target dimension
x[:,0]

In [ ]:
#get all values of 0th and 1 st dimension but only index of 1 and 2 dimension
x[:,:,1]

In [ ]:
#get all values of 0 dimnension but only the 1 index of 1st and 2nd dimension 
x[0, 1, 1]

In [ ]:
#get index o of oth and 1st dimension and all values of 2nd diemsnion 
x[0, 1, :]

In [ ]:
#index on x to return 9 
x (x[0[2[2]]])
# Index on x to return 3,6,9
print (x [:,:,2])



In [ ]:
x

## pytorch tensors and numpy 

numpy is  a popular scientific python numerical computing library .
And because of this , PyTorch has functionality to interact with it 
*  Data in numpy , want in pytorch tensor-> torch.from_numpy(ndarray)
*  pytorch tensor -> numpy-> torch.Tensor.numpy()

In [ ]:
#numpy array to tensor 
import torch 
import numpy as np

array =np.arange(1.0,8.0)
tensor= torch.from_numpy(array)#from converting numpy to pytorch reflects numpy's default datatype of float 64 unless specified otherwise 
array , tensor 


In [ ]:
array.dtype

In [ ]:
torch.arange(1.0,8.0).dtype

In [ ]:
tensor.dtype

In [ ]:
#change the value of array , what will this do this to 'tensor'?
array = array +1
array , tensor 


In [ ]:
#tensor to numpy array 
tensor = torch.ones (7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor 

In [ ]:
numpy_tensor.dtype 

In [ ]:
#change the tensor , what happens to "numpy_tensor"?
tensor = tensor + 1
tensor , numpy_tensor 

# Pytorch reproducibility ( trying to take the random out of random)

how a neural network learns is :
start with random numbers --- tensor operations -- update random numbers to try and make them of the data ...again ...again ....again 

In [ ]:
torch.rand(3,3)#generated randomness

To reduce the randomness in neural network and pytorch comes with the concept of **random Seed**

Essentially what the random seed does is "flavour" the randomness

In [ ]:
#create two random tensors
random_tensor_A= torch.rand(3,4)
random_tensor_B= torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print (random_tensor_A == random_tensor_B)





In [ ]:
#lets make random but reproducible tensors
import torch 
#set the random seed 
RANDOM_SEED = 42 
torch.manual_seed(RANDOM_SEED )

random_tensor_C = torch.rand(3,4)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

print (random_tensor_C == random_tensor_D)

torch.manual_seed(RANDOM_SEED)

random seed -- pseudo random number generator 

# ****Running tensors and pytorch objects on the GPUs (and making faster computations ****# 

In [ ]:
###getting a GPU
#check for GPU access with Pytorch 

import torch 
torch.cuda.is_available()

 



In [ ]:
#steup device agnostic code 

device = "cuda " if torch.cuda.is_available() else "Cpu"
device 

In [ ]:
#count the number of devices 
torch.cuda.device_count()

For pytorch since it is capable of running compute on the CPU or GPU it is best practice  to set up device 

In [ ]:
#putting tensors ( and models )on the GPU 
 #the reason we want our tensors on the GPU is because using a GPU results in faster computation

#create a tensor (default on the CPU)
tensor = torch.tensor ([1,2,3])

#tensor Not on GPU 

print (tensor, tensor.device )

move tensor to GPU ( if available ) 

In [ ]:
device = torch.device('cuda')
tensor_on_gpu = tensor.to(device)

# moving tensors back to the CPU

In [ ]:
# if tensor is on GPU , cant transform it to numpy 
# Move tensor to CPU first, then convert to numpy
numpy_array = tensor_on_gpu.cpu().numpy()
numpy_array = tensor_on_gpu.clone().cpu().numpy()  # original tensor stays on GPU

#READ DOCUMENTATION ON TORCH.TENSOR 
#READ DCOUMENTATION ON TORCH.CUDA

In [ ]:
#create a random tensor on torch.cuda 
import torch
# Create a 7x7 tensor with random values from a uniform distribution [0,1]
random_tensor = torch.rand(7, 7)
# For example, random values between 0 and 10
random_tensor = torch.rand(7, 7) * 10